
import java.util.Arrays;
import javax.swing.*;
import java.awt.event.*; 
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISlam
 */

public class Mframe extends javax.swing.JFrame {
     
        
      
         int counter=0;
         boolean b1ap=false,b2ap=false,b3ap=false,b4ap=false,b5ap=false
                ,b6ap=false,b7ap=false,b8ap=false,b9ap=false;//button already pressed.
        char[][] boardValue = new char[3][3];
    public Mframe() {
        initComponents();
        endDialog.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(25, 25, 25));
        btnStyleDefault(b1);
        btnStyleDefault(b2);
        btnStyleDefault(b3);
        btnStyleDefault(b4);
        btnStyleDefault(b5);
        btnStyleDefault(b6);
        btnStyleDefault(b7);
        btnStyleDefault(b8);
        btnStyleDefault(b9);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endDialog = new javax.swing.JDialog();
        endPanel = new javax.swing.JPanel();
        endText = new javax.swing.JTextField();
        endButton = new javax.swing.JButton();
        gBoard = new javax.swing.JPanel();
        b8 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        O = new javax.swing.JLabel();

        endDialog.setTitle("Game Over");
        endDialog.setAutoRequestFocus(false);
        endDialog.setFocusableWindowState(false);
        endDialog.setMinimumSize(new java.awt.Dimension(300, 140));
        endDialog.setResizable(false);

        endPanel.setBackground(new java.awt.Color(51, 51, 51));
        endPanel.setInheritsPopupMenu(true);
        endPanel.setMinimumSize(new java.awt.Dimension(286, 122));
        endPanel.setName(" "); // NOI18N

        endText.setEditable(false);
        endText.setBackground(new java.awt.Color(51, 51, 51));
        endText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        endText.setForeground(new java.awt.Color(204, 204, 0));
        endText.setBorder(null);
        endText.setFocusable(false);
        endText.setMinimumSize(new java.awt.Dimension(235, 53));
        endText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTextActionPerformed(evt);
            }
        });

        endButton.setBackground(new java.awt.Color(51, 0, 51));
        endButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        endButton.setForeground(new java.awt.Color(153, 255, 0));
        endButton.setText("Exit");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout endPanelLayout = new javax.swing.GroupLayout(endPanel);
        endPanel.setLayout(endPanelLayout);
        endPanelLayout.setHorizontalGroup(
            endPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(endPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(endText, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        endPanelLayout.setVerticalGroup(
            endPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(endText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout endDialogLayout = new javax.swing.GroupLayout(endDialog.getContentPane());
        endDialog.getContentPane().setLayout(endDialogLayout);
        endDialogLayout.setHorizontalGroup(
            endDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        endDialogLayout.setVerticalGroup(
            endDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-tac-toe");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon.png")).getImage());
        setName("Mframe"); // NOI18N

        gBoard.setBackground(new java.awt.Color(51, 0, 51));

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        X.setBackground(new java.awt.Color(255, 102, 102));
        X.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        O.setBackground(new java.awt.Color(49, 255, 255));
        O.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        O.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        O.setText("O");
        O.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(O, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(O, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gBoardLayout = new javax.swing.GroupLayout(gBoard);
        gBoard.setLayout(gBoardLayout);
        gBoardLayout.setHorizontalGroup(
            gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gBoardLayout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gBoardLayout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gBoardLayout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gBoardLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gBoardLayout.setVerticalGroup(
            gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(gBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(!b6ap&&!isWinner())
        {
            boardValue(1,2);
            btnIsPressed(b6);

            b6ap=true;
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(!b2ap&&!isWinner())
        {
            boardValue(0,1);
            btnIsPressed(b2);

            b2ap=true;
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(!b3ap&&!isWinner())
        {
            boardValue(0,2);
            btnIsPressed(b3);

            b3ap=true;

        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(!b5ap&&!isWinner())
        {
            boardValue(1,1);
            btnIsPressed(b5);

            b5ap=true;
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(!b9ap&&!isWinner())
        {

            boardValue(2,2);
            btnIsPressed(b9);
            b9ap=true;
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(!b7ap&&!isWinner())
        {
            boardValue(2,0);
            btnIsPressed(b7);

            b7ap=true;
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(!b1ap&&!isWinner())
        {
            boardValue(0,0);
            btnIsPressed(b1);

            b1ap=true;

        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(!b4ap&&!isWinner())
        {
            boardValue(1,0);
            btnIsPressed(b4);

            b4ap=true;
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(!b8ap&&!isWinner())
        {
            boardValue(2,1);
            btnIsPressed(b8);

            b8ap=true;
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_endButtonActionPerformed

    private void endTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTextActionPerformed
/*                  
    
    
                ***********The Functions place.******************
    
    
    
    
    
    */
    
        void boardValue(int i,int j){
            if(whoseTurn())
                boardValue[i][j]='O';
            else
                 boardValue[i][j]='X';
            //System.out.printf("%d   %d   %c \n",i,j,boardValue[i][j]); ***** debugging*******
        }
    
        boolean whoseTurn(){         //false for X and true for O
           return (counter%2==0);
        }
        
        void setIcon(javax.swing.JButton btn){
            if(whoseTurn())
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/O.png")));
            else
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/X.png")));
        }
       
        void btnIsPressed(javax.swing.JButton btn){
            counter++; // for whoseTurn()
            btn.setOpaque(true);
            btn.setContentAreaFilled(false);
            btn.setBorderPainted(false);
            setIcon(btn);
            labelColor();
           if(isWinner())
           { 
              // System.out.printf("Winner!!!!");    ******** debugging*****
               endDialog.setVisible(true);
               if(!whoseTurn())
               {endText.setText(" X player win!!!");endText.setForeground(new java.awt.Color(255, 102, 102));}
               else
               { endText.setText(" O player win!!!");endText.setForeground(new java.awt.Color(0, 204,255));}
        }
           if(counter==9&&!isWinner())
           {    
//               resetGame();
               endDialog.setVisible(true);
               endText.setText(" A draw.");
               
           }
        }
        
        
           void labelColor(){
        if(whoseTurn())
        {
            O.setBackground( new java.awt.Color(51, 0,51));
             //O.setForeground(new java.awt.Color(51, 0,51));
             X.setBackground(new java.awt.Color(255, 102, 102));
        }
        else
        {
              X.setBackground(new java.awt.Color(51, 0,51));
             // X.setForeground(new java.awt.Color(51, 0,51));
             O.setBackground( new java.awt.Color(0, 204,255));
        }
        }
        /*void resetGame(){
        counter=0;
        Arrays.fill(boardValue,'N');// N for Null.
        btnStyleDefault(b1);
        btnStyleDefault(b2);
        btnStyleDefault(b3);
        btnStyleDefault(b4);
        btnStyleDefault(b5);
        btnStyleDefault(b6);
        btnStyleDefault(b7);
        btnStyleDefault(b8);
        btnStyleDefault(b9);
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Null.png")));  
        b1ap=false;
        b2ap=false;  
        b3ap=false;  
        b4ap=false;  
        b5ap=false;  
        b6ap=false;  
        b7ap=false;  
        b8ap=false;  
        b9ap=false;  
        
        
        }*/
        boolean isWinner(){
        char val;
        char[][]T=boardValue;//T for testing.
        if(whoseTurn())
            val='X';
        else
            val='O';
        if(counter>=5)
        return((T[0][0]==val&&T[0][1]==val&&T[0][2]==val)||
                (T[1][0]==val&&T[1][1]==val&&T[1][2]==val)||
                (T[2][0]==val&&T[2][1]==val&&T[2][2]==val)||
                (T[0][0]==val&&T[1][1]==val&&T[2][2]==val)||
                (T[0][2]==val&&T[1][1]==val&&T[2][0]==val)||
                (T[0][0]==val&&T[1][0]==val&&T[2][0]==val)||
                (T[0][1]==val&&T[1][1]==val&&T[2][1]==val)||
                (T[0][2]==val&&T[1][2]==val&&T[2][2]==val));
        else return false;
        }
        
        void btnStyleDefault(javax.swing.JButton btn){
        btn.setBackground(new java.awt.Color(40, 40, 40));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        O.setBackground(new java.awt.Color(51, 0,51));
         //O.setForeground(new java.awt.Color(51, 0,51));
       
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel O;
    private javax.swing.JLabel X;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton endButton;
    private javax.swing.JDialog endDialog;
    private javax.swing.JPanel endPanel;
    private javax.swing.JTextField endText;
    private javax.swing.JPanel gBoard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
